### ISSUE TITLE
Correct syntax and errors in the code of account view

### ISSUE THREAD

**Issue by valen-ruggieri** [BC-MAY-21-RN/proyecto-final-m22-pf-t3-reactive-01#39]
# Description

# Tasks
   - [x]  Correct code and syntax
   - [x]  Modularize components for reuse and not to repeat code  
   - [x] Add function and design for reset / password change button
